# Generated by Django 5.2.7 on 2025-10-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseek_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='context_summary',
            field=models.TextField(blank=True, help_text='上下文摘要，用于压缩历史对话'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='conversation_type',
            field=models.CharField(choices=[('fault_analysis', '故障分析'), ('general_question', '一般问题'), ('follow_up', '跟进问题'), ('explanation', '解释请求'), ('prevention', '预防措施'), ('dependency', '依赖关系')], default='fault_analysis', help_text='当前对话类型', max_length=50),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='max_context_length',
            field=models.IntegerField(default=4000, help_text='最大上下文长度限制'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='recent_context',
            field=models.TextField(blank=True, help_text='最近N轮对话，保持完整格式'),
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('problem_identification', '问题识别'), ('root_cause_analysis', '根因分析'), ('solution_seeking', '解决方案寻求'), ('prevention_planning', '预防规划'), ('follow_up', '跟进讨论')], default='problem_identification', help_text='当前对话阶段', max_length=50)),
                ('analysis_depth', models.IntegerField(default=1, help_text='分析深度，表示对话轮次')),
                ('user_satisfaction', models.IntegerField(default=0, help_text='用户满意度评分 (0-5)')),
                ('last_analysis_result', models.JSONField(blank=True, help_text='上次分析结果，用于状态跟踪', null=True)),
                ('key_information', models.JSONField(default=dict, help_text='提取的关键信息（错误码、服务名等）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='关联的对话会话', on_delete=django.db.models.deletion.CASCADE, related_name='state', to='deepseek_api.conversationsession')),
            ],
            options={
                'verbose_name': '对话状态',
                'verbose_name_plural': '对话状态',
            },
        ),
    ]
